package com.projectivesoftware.distillehr.domain;

public enum DocumentType {
    MEDHOST_ENTERPRISE_FULL_ENCOUNTER_EXPORT,
    MEDHOST_ENTERPRISE_PATIENT_LOGIC_NOTE,
    MEDHOST_ENTERPRISE_ALLERGIES_ENCOUNTER_EXPORT,
    MEDHOST_ENTERPRISE_CARE_STANDARD_OVERRIDE_ENCOUNTER_EXPORT,
    MEDHOST_ENTERPRISE_INPATIENT_MEDICATION_ORDERS_ENCOUNTER_EXPORT,
    MEDHOST_ENTERPRISE_MEDICATION_ADMINISTRATION_ENCOUNTER_EXPORT,
    MEDHOST_ENTERPRISE_MEDICATION_RECONCILIATION_ENCOUNTER_EXPORT,
    MEDHOST_ENTERPRISE_ORDER_RESULTS_ENCOUNTER_EXPORT,
    MEDHOST_ENTERPRISE_ORDERS_ENCOUNTER_EXPORT,
    MEDHOST_ENTERPRISE_PATIENT_PROBLEMS_ENCOUNTER_EXPORT,
    MEDHOST_ENTERPRISE_VITALS_ENCOUNTER_EXPORT,
    HPF_EXPORT
}
